[package]
name = "trunic"
version = "0.2.0"
description = "Write runes from the Tunic video game"
authors = ["Dragonink <@Dragonink>"]
repository = "https://github.com/Dragonink/trunic.typ"
categories = ["fun", "languages"]

entrypoint = "src/lib.typ"
exclude = ["Makefile", "docs/*"]
